kafka.bootstrap-servers=${BOOTSTRAP_SERVER_URL:localhost:9092}

kafka.consumer.retry.max-attempts=${RETRY_MAX_ATTEMPTS:5}
kafka.consumer.retry.backoff-delay-ms=${RETRY_BACKOFF_DELAY_MS:1000}
kafka.consumer.concurrency=${CONSUMER_CONCURRENCY:1}
kafka.consumer.group=${CONSUMER_GROUP:chs-email-sender}
kafka.consumer.topic.email-send=${EMAIL_SEND_TOPIC:email-send}

management.endpoints.access.default=none
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=healthcheck
management.endpoint.health.show-details=never
management.endpoint.health.enabled=true
management.health.mongo.enabled=false
